### ISSUE TITLE
Problem with restart

### ISSUE THREAD

**Issue by SerdarSaglam** [CareF/deepin-dock-plugin-neoweather#11]
Hi
Sometimes does not appear automatically when restarted, Need to refresh manually

**Comment by CareF** [comment]
Thanks for feedback. Can you attache the log file at `~/.cache/deepin/dde-dock/dde-dock-plugin-weather.log`?

**Comment by TeknoMobil** [comment]
Thanks
`Start!
Weather Client inited.. cityid: 0 country: TR city: İstanbul
Check update: 2019/07/01 21:03:24
Connect: https://api.openweathermap.org/data/2.5/weather?q=İstanbul,TR&lang=en_US&units=metric&appid=1be2e3f645f5bca47fedfd6986a76972
Connect: https://api.openweathermap.org/data/2.5/forecast?q=İstanbul,TR&lang=en_US&units=metric&appid=1be2e3f645f5bca47fedfd6986a76972
Get reply: ...18:00:00"}],"city":{"id":745042,"name":"Ä°stanbul","coord":{"lat":41.0351,"lon":28.9833},"country":"TR","population":11581707,"timezone":10800}}
Parsing forecast for İstanbul, TR (id: 0)
Total 40 forcasts, first being:
	DateTime: 1969/12/16 08:05:04
	Weather: Clear, clear sky, icon 01n
	Temperature: 22.86
Get reply: ...1,"id":6970,"message":0.0083,"country":"TR","sunrise":1561948511,"sunset":1562002812},"timezone":10800,"id":745042,"name":"Ä°stanbul","cod":200}
Parsing weather for İstanbul, TR (id: 745042)
	DateTime: 1969/12/16 05:05:24
	Weather: Clear, clear sky, icon 01n
	Temperature: 23.98
Checking all done! Weather info arrived later
Check update: 2019/07/01 21:03:30
Connect: https://api.openweathermap.org/data/2.5/weather?id=745042&lang=en_US&units=metric&appid=1be2e3f645f5bca47fedfd6986a76972
Connect: https://api.openweathermap.org/data/2.5/forecast?id=745042&lang=en_US&units=metric&appid=1be2e3f645f5bca47fedfd6986a76972
Get reply: ...,"dt_txt":"2019-07-06 18:00:00"}],"city":{"id":745042,"name":"Ä°stanbul","coord":{"lat":41.0351,"lon":28.9833},"country":"TR","timezone":10800}}
Parsing forecast for İstanbul, TR (id: 745042)
Total 40 forcasts, first being:
	DateTime: 1969/12/16 08:05:04
	Weather: Clear, clear sky, icon 01n
	Temperature: 22.86
Get reply: ...1,"id":9708,"message":0.0072,"country":"TR","sunrise":1561948511,"sunset":1562002812},"timezone":10800,"id":745042,"name":"Ä°stanbul","cod":200}
Parsing weather for İstanbul, TR (id: 745042)
	DateTime: 1969/12/16 05:06:36
	Weather: Clear, clear sky, icon 01n
	Temperature: 23.91
Checking all done! Weather info arrived later
Check update: 2019/07/01 21:03:33
Connect: https://api.openweathermap.org/data/2.5/weather?id=745042&lang=en_US&units=metric&appid=1be2e3f645f5bca47fedfd6986a76972
Connect: https://api.openweathermap.org/data/2.5/forecast?id=745042&lang=en_US&units=metric&appid=1be2e3f645f5bca47fedfd6986a76972
Get reply: ...1,"id":9708,"message":0.0072,"country":"TR","sunrise":1561948511,"sunset":1562002812},"timezone":10800,"id":745042,"name":"Ä°stanbul","cod":200}
Parsing weather for İstanbul, TR (id: 745042)
	DateTime: 1969/12/16 05:06:36
	Weather: Clear, clear sky, icon 01n
	Temperature: 23.91
Get reply: ...,"dt_txt":"2019-07-06 18:00:00"}],"city":{"id":745042,"name":"Ä°stanbul","coord":{"lat":41.0351,"lon":28.9833},"country":"TR","timezone":10800}}
Parsing forecast for İstanbul, TR (id: 745042)
Total 40 forcasts, first being:
	DateTime: 1969/12/16 08:05:04
	Weather: Clear, clear sky, icon 01n
	Temperature: 22.86
Checking all done! Forecast info arrived later
Check update: 2019/07/01 21:03:46
Connect: https://api.openweathermap.org/data/2.5/weather?id=745042&lang=en_US&units=metric&appid=1be2e3f645f5bca47fedfd6986a76972
Connect: https://api.openweathermap.org/data/2.5/forecast?id=745042&lang=en_US&units=metric&appid=1be2e3f645f5bca47fedfd6986a76972
Get reply: ...1,"id":9708,"message":0.0072,"country":"TR","sunrise":1561948511,"sunset":1562002812},"timezone":10800,"id":745042,"name":"Ä°stanbul","cod":200}
Parsing weather for İstanbul, TR (id: 745042)
	DateTime: 1969/12/16 05:06:36
	Weather: Clear, clear sky, icon 01n
	Temperature: 23.91
Get reply: ...,"dt_txt":"2019-07-06 18:00:00"}],"city":{"id":745042,"name":"Ä°stanbul","coord":{"lat":41.0351,"lon":28.9833},"country":"TR","timezone":10800}}
Parsing forecast for İstanbul, TR (id: 745042)
Total 40 forcasts, first being:
	DateTime: 1969/12/16 08:05:04
	Weather: Clear, clear sky, icon 01n
	Temperature: 22.86
Checking all done! Forecast info arrived later`

**Comment by TeknoMobil** [comment]
Sometimes it's not a problem, sometimes it's a problem

![DeepinScreenshot_dde-desktop_20190701213609](https://user-images.githubusercontent.com/42881121/60458890-6ce47280-9c48-11e9-8adc-c2af3b66c52d.png)

**Comment by CareF** [comment]
The log looks right.... 
Can you stop the plugin, delete the log and restart again, get the log when it's an issue?

**Comment by TeknoMobil** [comment]
It's only in fashion mode.
`Start!
Weather Client inited.. cityid: 0 country: TR city: İstanbul
Check update: 2019/07/01 21:54:42
Connect: https://api.openweathermap.org/data/2.5/weather?q=İstanbul,TR&lang=en_US&units=metric&appid=1be2e3f645f5bca47fedfd6986a76972
Connect: https://api.openweathermap.org/data/2.5/forecast?q=İstanbul,TR&lang=en_US&units=metric&appid=1be2e3f645f5bca47fedfd6986a76972
Get reply: ...18:00:00"}],"city":{"id":745042,"name":"Ä°stanbul","coord":{"lat":41.0351,"lon":28.9833},"country":"TR","population":11581707,"timezone":10800}}
Parsing forecast for İstanbul, TR (id: 0)
Total 40 forcasts, first being:
	DateTime: 1969/12/16 08:05:04
	Weather: Clear, clear sky, icon 01n
	Temperature: 22.12
Get reply: ...1,"id":6970,"message":0.0063,"country":"TR","sunrise":1561948511,"sunset":1562002812},"timezone":10800,"id":745042,"name":"Ä°stanbul","cod":200}
Parsing weather for İstanbul, TR (id: 745042)
	DateTime: 1969/12/16 05:55:20
	Weather: Clear, clear sky, icon 01n
	Temperature: 23.05
Checking all done! Weather info arrived later`

**Comment by CareF** [comment]
This is weird... 
When you say restart, do you mean restart the whole system or just restart the dock?

**Comment by TeknoMobil** [comment]
Restart from normal menu.
Could it be because the network isn't ready yet? Fast opening in average 12 -15 seconds

**Comment by CareF** [comment]
It's possible. Can you try kill the dock in terminal `pkill dde-dock` and wait it restart, and see if it's alright?

**Comment by TeknoMobil** [comment]
Yes (pkill dde-dock) corrects with code

**Comment by TeknoMobil** [comment]
The second time I tried the same code again, the data stream did not come back

**Comment by CareF** [comment]
So it looks like the issue is when restart the computer, the network is not ready when loading the plugin. 

I'll keep this in mind when I improve the plugin, but it may require improvement of the updating logic.

**Comment by TeknoMobil** [comment]
Thank you, my English is not very good.
A small video:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/42881121/60461688-f8adcd00-9c4f-11e9-9972-262a51d73e6c.gif)

**Comment by CareF** [comment]
OK.. I get what you mean. Not loading the correct icon is definitely a bug. I'll look into that.
