### ISSUE TITLE
Icon design

### ISSUE THREAD

**Issue by CareF** [CareF/deepin-dock-plugin-neoweather#4]
Unless you still want to play around with different icon designs, adding new icon sets is of lower priority at this stage I think. What about this: Let's decide on two or three sets, merge it to master and do a beta release. At the same time, let's start working on applet design. 

For what we already have, I prefer neoGray and neoGC, but I think I can make the feature that adds frames for icons on dock, but leave applet the same. What I will need is a separate image file with only the frame (circle or square, I prefer circle). 

And BTW, I think comments on commits is not a good way of sharing ideas because it's not listed together. I prefer to attach links to commits within an issue post. 

@aiamuzz

**Comment by aiamuzz** [comment]
> Unless you still want to play around with different icon designs, adding new icon sets is of lower priority at this stage I think. What about this: Let's decide on two or three sets, merge it to master and do a beta release. At the same time, let's start working on applet design.

yes ... will release icons to master only if they turnout really well on the applet ... for now ... you can add these 3 to beta ... 
neoGray
neoColor (i'll be improving the color shades some more )
neoGC

> 
> but I think I can make the feature that adds frames for icons on dock, but leave applet the same. What I will need is a separate image file with only the frame (circle or square, I prefer circle).

ok ... but can we keep this as an option to the user to choose from ... as i personally like the neoGray icons on the dock without any background ... it really comes to gether well with the Deepin UI ... 

may be radio button for a 'icons on dock' which has ...

gray (could be the neoGray icon)
color (the color option when selected will render the icon in dock with the background you are suggesting)

> And BTW, I think comments on commits is not a good way of sharing ideas because it's not listed together. I prefer to attach links to commits within an issue post.

ok ... learning as i go ... you mean we could keep the comments in the conversation section ?

**Comment by CareF** [comment]
@aiamuzz For icons on the dock, you are the designer so if you don't like it, we don't do it. 
For comments on commits, I mean I don't like comments for e.g. here https://github.com/CareF/deepin-dock-plugin-neoweather/commit/ed3d11db40999f1b14421121b5b174bb74cc8ab2#comments

**Comment by aiamuzz** [comment]
@CareF ... thanks ...
