### ISSUE TITLE
Night icon implementation in the applet seems off !

### ISSUE THREAD

**Issue by aiamuzz** [CareF/deepin-dock-plugin-neoweather#6]
@CareF ... 

![deepinscreenshot_select-area_20190210152228](https://user-images.githubusercontent.com/3283676/52534937-11374c80-2d6e-11e9-8904-6c37eed94d73.png)

This screenshot was taken at around 3:30 pm my local time ... but as you can see in the above screenshot the night versions of the icons(with stars) are showing up in the weather applet.

Shouldn't the night icons be triggered only between a certain time frame ... say 6:00 pm to 6:00 am ?

please look into the same ...

**Comment by aiamuzz** [comment]
the primary icon for today is showing correctly both on the applet as well as on the dock ...

only the icons for the forecast for the next 5 days is where the icons are misfiring(showing night icons) ... seems the code needs to be corrected for the day cycle as it seems the **Forecast Data(5 day)** is currently programmed to display as a night cycle all throughout.

**Comment by CareF** [comment]
This is a good point. 
The information we can get from openweathermap is 3-hour forecasts in the following 5 days, including icon names. 
Originally in sonichy's plugin and in mine before, weather in 12pm is used for weather of the day. I don't feel comfortable with this, so I changed to a statistics that look for primary weather and temperature ranges. The icon is the time when there's primary weather, and the earliest. "clear sky" is of the lowest priority in "primary weather" search. So when you see this it means that the whole day is "clear sky" and the plugin get the lowest one. And for night icon of rain, rain has higher priority in primary weather search than clear, so when you see the night icon, it means it rain at night. 
There are two possible solutions: 
1. regardless, change all night icons into day icons in forecasts; 
2. add a time dependence when doing statistics, and looking for day time weather.

**Comment by aiamuzz** [comment]
> This is a good point.
> The information we can get from openweathermap is 3-hour forecasts in the following 5 days, including icon names.

So are you saying that openweathermap updates forecast in 3 hour intervals ... for current days as well as the coming days ?


> There are two possible solutions:
> 
> 1. regardless, change all night icons into day icons in forecasts;
> 2. add a time dependence when doing statistics, and looking for day time weather.

I believe the 2 option should be the direction we take(given its achievability) ... In lay man terms ... i as a user would prefer the current time (When the user views our weather applet ) as the point of reference ...

i guess we need to first define the night cycle and day cycle clealy ... 6:00 to 6:00 is a good split ...

Now Say i click on the weather icon at 3 pm ... I would do it with the intention of know what the weather is going to be for the next 3 hours(which is the openweathemaps protocol of update) on that day ...

But when trying to use the forecast information ... the simplest way a user could comprehend it would be by taking into account the time of viewing of the information in the applet ... which is 3:00 pm ... if we consider this time and display forecast information for those days between 3:00pm and 6:00pm the user would have made sense of the forecast information and can use it in planning his furture events and our plugin with its forecast information would have given him actionable data.


One better would be ... If openweathermaps really has the 3 hourly forecast information for the coming days as well ... then ...  A more advanced and ideal system could be designed ... where the user could choose from a 24 hour time slot or a time slider ... to browse through the forecast data for the next 5 days this will empower the user to plan their events based on the forecast ... which is the true spirit of any forecast data ... A user could have a higher level of utility out of such a system ... by looking for the forecast weather information around the events that he already has planned in is scheduler !!!

This would be a really powerful utility for any user ... Don't you think ? ... Again this system is subject to the feasibility of implementing it and the availability of such a data for the coming days !!!


But if the 3 hourly information is available ONLY for the next 3 hours ... then your option first option of changing all night icons into day icons could be implemented i guess ... as a layman user would not be able to understand the complex system of priorities !!!

**Comment by CareF** [comment]
@aiamuzz 
https://openweathermap.org/forecast5
This is the document for openweathermap API. I think I mentioned it before. More details about what we can get can be found there. 
And I don't want to make the plugin too complicated in terms of user settings. It doesn't make sense for users to learn how it work before they are able to use it.

**Comment by aiamuzz** [comment]
> @aiamuzz
> https://openweathermap.org/forecast5
> This is the document for openweathermap API. I think I mentioned it before. More details about what we can get can be found there.
> And I don't want to make the plugin too complicated in terms of user settings. It doesn't make sense for users to learn how it work before they are able to use it.

Yes ... you had directed me to their API ... I just read it on the surface ... did not dive deep ...

I just created a account there let me try to dive into it as much as i can afford ... the technical terms could drown me ... but i'll try to stay afloat ... :)

**Comment by CareF** [comment]
So any suggestion how we should design this? 
Just in case you didn't find the API info, 3-hour forecast is for future, starting a few hours later (in their documents the specific time is not provided). 
But for what we display, in the applet currently the first row is today's forecast, the following is the next 5 days. (Also see https://github.com/CareF/deepin-dock-plugin-neoweather/issues/7 )

So my proposals are: 
1. regardless, change all night icons into day icons in forecasts;
2. add a time preference when doing statistics, and looking for day time weather only. 

What do you prefer? Or any other ideas?

**Comment by aiamuzz** [comment]
@CareF ...

Here is a sample openweather info for 12 Feb 2019 ...

"dt_txt":"2019-02-12 00:00:00"},{"dt":1549940400,"main":{"temp":288.043,"temp_min":288.043,"temp_max":288.043,"pressure":931.12,"sea_level":1029.24,"grnd_level":931.12,"humidity":97,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"**01n**"}],"clouds":{"all":0},"wind":{"speed":3.62,"deg":90.5004},"rain":{},"sys":{"pod":"n"},

"dt_txt":"2019-02-12 00:00:00"},{"dt":1549940400,"main":{"temp":290.55,"temp_min":290.55,"temp_max":290.55,"pressure":933.06,"sea_level":1031.07,"grnd_level":933.06,"humidity":95,"temp_kf":0},"weather":[{"id":500,"main":"Rain","description":"light rain","icon":"**10d**"}],"clouds":{"all":0},"wind":{"speed":4.31,"deg":94.0026},"rain":{"3h":0.02},"sys":{"pod":"d"},

"dt_txt":"2019-02-12 **03:00:00**"},{"dt":1549951200,"main":{"temp":298.446,"temp_min":298.446,"temp_max":298.446,"pressure":933.17,"sea_level":1030.07,"grnd_level":933.17,"humidity":61,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"**01d**"}],"clouds":{"all":0},"wind":{"speed":5.02,"deg":96.0018},"rain":{},"sys":{"pod":"d"},

"dt_txt":"2019-02-12 **06:00:00**"},{"dt":1549962000,"main":{"temp":301.383,"temp_min":301.383,"temp_max":301.383,"pressure":930.81,"sea_level":1026.97,"grnd_level":930.81,"humidity":47,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"**01d**"}],"clouds":{"all":0},"wind":{"speed":5.82,"deg":94.5028},"rain":{},"sys":{"pod":"d"},

"dt_txt":"2019-02-12 **09:00:00**"},{"dt":1549972800,"main":{"temp":300.16,"temp_min":300.16,"temp_max":300.16,"pressure":930.47,"sea_level":1026.76,"grnd_level":930.47,"humidity":45,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"**01d**"}],"clouds":{"all":0},"wind":{"speed":5.55,"deg":96.504},"rain":{},"sys":{"pod":"d"},

"dt_txt":"2019-02-12 **12:00:00**"},{"dt":1549983600,"main":{"temp":295.502,"temp_min":295.502,"temp_max":295.502,"pressure":932.77,"sea_level":1029.73,"grnd_level":932.77,"humidity":61,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"**01n**"}],"clouds":{"all":0},"wind":{"speed":4.77,"deg":102.004},"rain":{},"sys":{"pod":"n"},

"dt_txt":"2019-02-12 **15:00:00**"},{"dt":1549994400,"main":{"temp":292.144,"temp_min":292.144,"temp_max":292.144,"pressure":933.77,"sea_level":1031.32,"grnd_level":933.77,"humidity":69,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"**01n**"}],"clouds":{"all":0},"wind":{"speed":4.38,"deg":95.0059},"rain":{},"sys":{"pod":"n"},

"dt_txt":"2019-02-12 **18:00:00**"},{"dt":1550005200,"main":{"temp":288.791,"temp_min":288.791,"temp_max":288.791,"pressure":932.61,"sea_level":1030.61,"grnd_level":932.61,"humidity":87,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"**01n**"}],"clouds":{"all":0},"wind":{"speed":3.47,"deg":88.0061},"rain":{},"sys":{"pod":"n"},

"dt_txt":"2019-02-12 **21:00:00**"},{"dt":1550016000,"main":{"temp":286.823,"temp_min":286.823,"temp_max":286.823,"pressure":932.39,"sea_level":1030.7,"grnd_level":932.39,"humidity":95,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"**01n**"}],"clouds":{"all":0},"wind":{"speed":3.22,"deg":85.0002},"rain":{},"sys":{"pod":"n"},

Wouldn't it be simple if we showed the exact same icon for each 3 hour time slot openweathermap serves as seen above(marked in bold) ... instead of the continuous night icon on the forecast we could switch the icons according to the openweathermaps icon ... i can see that there are day icons too during the day ... Also this way the user will get the forecast information of those days and the weather around the time of checking(viewing) the weather applet !!!

One other thing i would like changed is to drop the temperature range for the current day ... Say i am a user and in my region i suddenly feel has turned very hot or very cold ... i would check the weather applet to see what is the current **REALTIME** temperature at that moment and NOT the min-max temperature ... a more accurate exact temperature at the time of viewing displayed for the current day is more useful !!! ... something like this ... google search for the word temperature shows the following realtime info !!!

![image](https://user-images.githubusercontent.com/3283676/52689080-fab40f80-2f7e-11e9-9b1a-1a7193d6a4c6.png)

Does openweathermap have realtime exact temperature ? If not then i guess we need to consider picking this information from some other realtime updating weather system ...

**Comment by CareF** [comment]
The icon on dock, and if efficient mode, temperature and weather info on dock, is real time weather, from 
https://openweathermap.org/current
The first row in applet is the statistic of the remaining of the day if there's any, otherwise it's real time.

**Comment by CareF** [comment]
And hey, we are planning to replace the applet, aren't we? 
From the API documents I sent you, I think you should be able to tell what we can get from openweathermap, and our purpose I think is not to do fine adjustment on the applet but design a new one. Unless you are satisfied with the overall design of the applet.
